// <auto-generated />
namespace BeerHunter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class inclusao_id_api : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inclusao_id_api));
        
        string IMigrationMetadata.Id
        {
            get { return "201912071544327_inclusao_id_api"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
